# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploying the file

on:
  push:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy the app
      run: |
        npm install
        sed -i '8 i $quoteAnimationNames: false;' ./node_modules/vue2-animate/src/sass/make-transitions.scss
        npm run build
        echo "Updating some files"
        rm ./dist/manifest.json
        cp ./tenous_files/404.html ./dist/
        cp ./tenous_files/.htaccess ./dist/
        cp ./tenous_files/manifest.json ./dist/
        cp ./sitemap.xml ./dist/
        echo "Deploying to the server..."
        scp -rp dist/* {{ secrets.DEPLOY_KEY }}
        scp dist/.htaccess {{ secrets.DEPLOY_KEY }}
        echo "Work finished"
