name: Continous Integration for Portfolio

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and test
      run: |
        npm install
        sed -i '8 i $quoteAnimationNames: false;' ./node_modules/vue2-animate/src/sass/make-transitions.scss
        npm run build
        npm test
